### ISSUE TITLE
websock failed to connect to mqtt

### ISSUE THREAD

**Issue by qinjinze** [fhmq/hmq#123]
Connection address ws://xxx.xxx.xxx.xxx:1888/ws
Prompt that the connection failed

**Comment by vipul-mi** [comment]
> Connection address ws://xxx.xxx.xxx.xxx:1888/ws Prompt that the connection failed

Same error for me
@muXxer @luca-moser Anyone can help and provide sample for that?

**Comment by lucasvmx** [comment]
@qinjinze @vipul-mi this error persists?

**Comment by lucasvmx** [comment]
@qinjinze @vipul-mi take a look:

# Configure connection
![image](https://user-images.githubusercontent.com/13322110/166117286-3b92a740-1b46-4019-b3ed-b381604022da.png)

# Subscribe to topic
![image](https://user-images.githubusercontent.com/13322110/166117311-256d976e-7148-4347-bd5e-6874d6fd6b4b.png)

# Publish a payload
![image](https://user-images.githubusercontent.com/13322110/166117359-7952ed76-d941-42ff-b27f-40af122ef810.png)
