### ISSUE TITLE
Offer of code: Mods to plugin f/work

### ISSUE THREAD

**Issue by thinkovation** [fhmq/hmq#129]
Hello!

I've developed a bridge plugin for audit / debugging that outputs messages to a CSV file using a worker. The plugin allows you to define filters using the same syntax as the topic acls (eg "roottopic/subtopic/+/alerts", "roottopic/subtopic/#" etc).

I am also working on allowing multiple plugins to be loaded so you can republish to more than one bridge.

More than happy to submit a PR if you're interested?

**Comment by chowyu08** [comment]
welcome your PR

**Comment by thinkovation** [comment]
Thanks for committing my pr!
