### ISSUE TITLE
"msg":"read packet error: ","error":"EOF"

### ISSUE THREAD

**Issue by andrewvdp** [fhmq/hmq#132]
We are running the service in a docker container in Kubernetes. Connections come through a proxy using traefik but each connection drops after about 30 seconds. Here is an example of an error message 
```
{"level":"error","timestamp":"2021-11-09T22:16:50.676Z","logger":"broker","caller":"broker/client.go:131","msg":"read packet error: ","error":"EOF","ClientID":"id","stacktrace":"github.com/fhmq/hmq/broker.(*client).readLoop\n\t/go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20200119031921-55f1f1aa8001/broker/client.go:131\ngithub.com/fhmq/hmq/broker.(*Broker).handleConnection\n\t/go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20200119031921-55f1f1aa8001/broker/broker.go:369"}
```
Any help of suggestions would be greatly appreciated!

**Comment by je-martinez** [comment]
@andrewvdp How did you resolve this issue? I got this error on a Kubernetes Cluster on Digital Ocean, I am able to connect to the broker but I receive that log every 30 seconds.
