### ISSUE TITLE
Can I disconnect the connected mqtt connections by clientId or username ?

### ISSUE THREAD

**Issue by Shoothzj** [fhmq/hmq#133]
Can I disconnect the connected mqtt connections by clientId or username ? :)
Thanks for your help

**Comment by chowyu12** [comment]
you can get client from [https://github.com/fhmq/hmq/blob/8d486c3a208ffc8b93a8fb120af42c687f4221e6/broker/broker.go#L40](L40) by clientID, and Close it

**Comment by Shoothzj** [comment]
> you can get client from https://github.com/fhmq/hmq/blob/master/broker/broker.go#L40 by clientID, and Close it

@chowyu12 thank you, do I need to remove it from `sync.Map` too, or it will clean automatic

**Comment by Shoothzj** [comment]
@chowyu12 It's a private member, how could I get that?

**Comment by chowyu12** [comment]
@Shoothzj  close and remove it from sync.Map

**Comment by Shoothzj** [comment]
@chowyu12 It's a private member, how could I get that? :)

**Comment by chowyu12** [comment]
you can push a pr
