### ISSUE TITLE
Can bridgeMq receive the qos configurations

### ISSUE THREAD

**Issue by shoothzj** [fhmq/hmq#140]
Can bridgeMq receive the qos configurations? To control a message if acked ?
Thanks for your reply!

**Comment by chowyu12** [comment]
To control a message if acked ?

**Comment by Shoothzj** [comment]
> To control a message if acked ?

Yes, like if custom logic failed, don't ack :)

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by chowyu12** [comment]
you mean sync publish message to mq?

**Comment by Shoothzj** [comment]
> you mean sync publish message to mq?

yes.

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by Shoothzj** [comment]
@chowyu08 ping

**Comment by Shoothzj** [comment]
@chowyu08 ping
