### ISSUE TITLE
Can't we deal with a chan  instead of an array of MessagePool?

### ISSUE THREAD

**Issue by MarcMagnin** [fhmq/hmq#15]
https://github.com/fhmq/hmq/blob/221d00480eb5dd060b2eb24ec31bbb2e4a51d1d8/broker/msgpool.go#L24

I was wondering if we couldn't replace the MessagePool array by a chan?
This would enable us to remove a bunch of goroutines in the dispatcher.

**Comment by MarcMagnin** [comment]
I've done some tests and it's seems to behave fine. I'll raise a PR when the code looks ok. Let me know if you can think of any potential issue. It should save us from spawning 1024 goroutines.

**Comment by MarcMagnin** [comment]
Maybe we can entirely skip the MessagePool chan and just call go ProcessMessage(msg) on message reception. That would dramatically increase the performances. Do you think of any issue regarding this?
More details about channels perfs: https://syslog.ravelin.com/so-just-how-fast-are-channels-anyway-4c156a407e45

**Comment by MarcMagnin** [comment]
Well, probably not. The cost of spawning new go routines should be higher.

**Comment by MarcMagnin** [comment]
What about implementing this?: https://github.com/textnode/gringo

**Comment by chowyu08** [comment]
use a channel may good idea to ensure that the timing of the message

**Comment by MarcMagnin** [comment]
I've replaced MSGPool []MessagePool by a single chan *Message and it seems to behave fine.
Then we don't need a goroutine and worker per MessagePool which enable us to do the job with far less workers. It seems to behave just fine and if there is no particular reason to have multiple Message queues then I think it's a better way.
Let me know if you want a PR to have a look at it.

**Comment by MarcMagnin** [comment]
I've tested Gringo and the problem with it is that it's not blocking workers loop so it consumes 100% of the CPU :/ I think you can go ahead with the branch "pool" as it solves that issue.
