### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by lucasvmx** [fhmq/hmq#152]
# How to reproduce
 - `go run -race main.go`
 - `mosquitto_sub -t test -i "evil subscriber"`
 - `mosquitto_pub -t test -m "publisher 123" -q 1`
 - wait ~20 seconds (see broker/client.go line 48) -> retryInterval
 ![image](https://user-images.githubusercontent.com/13322110/161161895-35fc5fe3-0456-4d7e-b510-fb8f66938088.png)
 - Race condition should be triggered

# Logs
```json
{"level":"info","timestamp":"2022-03-31T19:59:32.516-0300","logger":"broker","caller":"broker/broker.go:286","msg":"read connect from ","clientID":"evil subscriber"}
{"level":"info","timestamp":"2022-03-31T19:59:35.118-0300","logger":"broker","caller":"broker/broker.go:286","msg":"read connect from ","clientID":"evil publisher"}
```

# Result
WARNING: DATA RACE
Read at 0x00c0007f81a8 by goroutine 1111:
  github.com/fhmq/hmq/broker.(*client).resetRetryTimer()
      /home/lucas/Desktop/projetos/hmq/broker/comm.go:184 +0x3e

Previous write at 0x00c0007f81a8 by goroutine 647:
  github.com/fhmq/hmq/broker.(*client).ensureRetryTimer()
      /home/lucas/Desktop/projetos/hmq/broker/comm.go:178 +0x129

**Comment by Shoothzj** [comment]
@lucas-engen @chowyu08 this issue can be closed
