### ISSUE TITLE
websocket  {"level":"info","timestamp":"2022-04-13T16:51:45.837+0800","logger":"broker","caller":"broker/broker.go:315","msg":"read connect from ","clientID":"mqttx_4f7039f8","addrError":"PANIC=runtime error: invalid memory address or nil pointer dereference"}

### ISSUE THREAD

**Issue by coconutsheep** [fhmq/hmq#161]

**Comment by coconutsheep** [comment]
go run main.go -ws 1888 -wsp /ws

**Comment by coconutsheep** [comment]
go run main.go -ws 1888 -wsp /ws   Did I use it wrong or BUG
![image](https://user-images.githubusercontent.com/92964197/163142808-599867ee-8cb6-49a1-a47c-a0f9afb98286.png)
![image](https://user-images.githubusercontent.com/92964197/163142926-ba161556-8d7d-4075-a3bc-cd7dde5584dc.png)
![2f12561569327ab89d65b326e3aafe9](https://user-images.githubusercontent.com/92964197/163142834-9e6cf405-fd9d-4f9f-a58a-4e87a8850e5b.png)

**Comment by lucas-engen** [comment]
@coconutsheep i'm unable to reproduce this issue

Here i got: 

```json
{"level":"error","timestamp":"2022-04-25T21:35:02.157-0300","logger":"broker","caller":"broker/broker.go:311","msg":"received msg that was not Connect"}
```

**Comment by lucasvmx** [comment]
@chowyu08 this issue can be closed
