### ISSUE TITLE
Can't do "go get ..."

### ISSUE THREAD

**Issue by MarcMagnin** [fhmq/hmq#2]
Hi, 

Thanks a lot for this project!
I'd like to use your project as a dependency with "go get github.com/fhmq/hmq" but I got the following error: 
```
package hmq/broker: unrecognized import path "hmq/broker" (import path does not begin with hostname)
```
Any idea on that one?
Many thanks

**Comment by MarcMagnin** [comment]
I think I've found what the problem is. Shall I go ahead and create a PR?

**Comment by chowyu08** [comment]
yes, thank you
