### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lukaizhi** [fhmq/hmq#26]
{"level":"error","ts":1523360297.1253836,"logger":"hmq.Broker","caller":"broker/client.go:251","msg":"process message for psub error,  ","error":"write tcp 172.31.58.23:10086->14.26.19.135:25134: use of closed network connection","ClientID":"A1020180316031600"}
{"level":"error","ts":1523360297.1254902,"logger":"hmq.Broker","caller":"broker/client.go:251","msg":"process message for psub error,  ","error":"write tcp 172.31.58.23:10086->14.26.19.135:25134: use of closed network connection","ClientID":"A1020180316031600"}
{"level":"error","ts":1523360297.125594,"logger":"hmq.Broker","caller":"broker/client.go:251","msg":"process message for psub error,  ","error":"write tcp 172.31.58.23:10086->14.26.19.135:25134: use of closed network connection","ClientID":"A1020180316031600"}
{"level":"error","ts":1523360297.1257198,"logger":"hmq.Broker","caller":"broker/client.go:251","msg":"process message for psub error,  ","error":"write tcp 172.31.58.23:10086->14.26.19.135:25134: use of closed network connection","ClientID":"A1020180316031600"}
{"level":"error","ts":1523360297.125832,"logger":"hmq.Broker","caller":"broker/client.go:251","msg":"process message for psub error,  ","error":"write tcp 172.31.58.23:10086->14.26.19.135:25134: use of closed network connection","ClientID":"A1020180316031600"}
{"level":"error","ts":1523360297.146843,"logger":"hmq.Broker","caller":"broker/client.go:127","msg":"read packet error: ","error":"read tcp 172.31.58.23:10086->14.26.19.135:25134: use of closed network connection","ClientID":"A10201803160316"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x661b4a]

goroutine 1468 [running]:
panic(0x6d07e0, 0x8db7b0)
	C:/Go/src/runtime/panic.go:554 +0x3c1 fp=0xc421337278 sp=0xc4213371d8 pc=0x429551
runtime.panicmem()
	C:/Go/src/runtime/panic.go:63 +0x5e fp=0xc421337298 sp=0xc421337278 pc=0x42842e
runtime.sigpanic()
	C:/Go/src/runtime/signal_unix.go:388 +0x17a fp=0xc4213372e8 sp=0xc421337298 pc=0x43e6ca
github.com/eclipse/paho.mqtt.golang/packets.(*PublishPacket).Write(0xc421220440, 0x0, 0x0, 0x0, 0x0)
	C:/Users/lukz/go/src/github.com/eclipse/paho.mqtt.golang/packets/publish.go:39 +0x25a fp=0xc421337430 sp=0xc4213372e8 pc=0x661b4a
github.com/fhmq/hmq/broker.(*client).WriterPacket(0xc420c1b590, 0x771f40, 0xc421220440, 0xc420f93c50, 0x905f60)
	E:/go/src/github.com/fhmq/hmq/broker/client.go:534 +0xb2 fp=0xc421337488 sp=0xc421337430 pc=0x678a72
github.com/fhmq/hmq/broker.(*client).ProcessPublishMessage(0xc420c1a5a0, 0xc421220440)
	E:/go/src/github.com/fhmq/hmq/broker/client.go:249 +0x124 fp=0xc421337868 sp=0xc421337488 pc=0x675a24
github.com/fhmq/hmq/broker.(*client).ProcessPublish(0xc420c1a5a0, 0xc421220440)
	E:/go/src/github.com/fhmq/hmq/broker/client.go:198 +0x87c fp=0xc421337d70 sp=0xc421337868 pc=0x6755ec
github.com/fhmq/hmq/broker.ProcessMessage(0xc420f117e0)
	E:/go/src/github.com/fhmq/hmq/broker/client.go:157 +0x574 fp=0xc421337f70 sp=0xc421337d70 pc=0x674c14
github.com/fhmq/hmq/broker.(*Broker).StartDispatcher.func1.1()
	E:/go/src/github.com/fhmq/hmq/broker/broker.go:102 +0x2a fp=0xc421337f88 sp=0xc421337f70 pc=0x68097a
github.com/fhmq/hmq/pool.startWorker.func1(0xc420018300, 0xc4200523c0)
	E:/go/src/github.com/fhmq/hmq/pool/pool.go:160 +0x68 fp=0xc421337fd0 sp=0xc421337f88 pc=0x665ed8
runtime.goexit()
	C:/Go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc421337fd8 sp=0xc421337fd0 pc=0x456811
created by github.com/fhmq/hmq/pool.startWorker
	E:/go/src/github.com/fhmq/hmq/pool/pool.go:145 +0x49

**Comment by JaosnHsieh** [comment]
did u find any solutions for this error?
