### ISSUE TITLE
error here when build

### ISSUE THREAD

**Issue by svija** [fhmq/hmq#32]
[root@iz2zeamz4btzv5e42dk6hsz mqtt]# go run main.go
# go.uber.org/zap
/usr/local/go/src/go.uber.org/zap/field.go:10: syntax error: unexpected = in type declaration

**Comment by lucas-engen** [comment]
You still getting this error?

**Comment by lucas-engen** [comment]
```sh
user@pc:~/Desktop/hmq$ go run main.go
{"level":"info","timestamp":"2021-02-25T15:12:07.336-0500","logger":"broker","caller":"broker/broker.go:193","msg":"Start Listening client on ","hp":"0.0.0.0:1883"}

```

**Comment by lucas-engen** [comment]
@chowyu08 i think that this issue can be closed
