### ISSUE TITLE
[bug?]routes->remotes

### ISSUE THREAD

**Issue by husy1994** [fhmq/hmq#45]
In  broker/broker.go, does it should be b.remotes instead of b.routes? since the client objects in b.routes do not have an initialized session object, which will lead to a panic.

```Go
func (b *Broker) BroadcastSubOrUnsubMessage(packet packets.ControlPacket) {
	b.remotes.Range(func(key, value interface{}) bool {
		r, ok := value.(*client)
		if ok {
			r.WriterPacket(packet)
		}
		return true
	})
	// log.Info("BroadcastSubscribeMessage remotes: ", s.remotes)
}
```

**Comment by chowyu08** [comment]
remote just connect to router to receive cluster url list,  route connect other node,  for message route.

**Comment by husy1994** [comment]
> remote just connect to router to receive cluster url list, route connect other node, for message route.

In my understanding, the function _connectRouter_ in broker/broker.go is used to connect other brokers, and the corresponding clientA is stored in brokerA.remotes.   But the counterpart brokerB handle this connection by _handleConnection_ function, and stores the corresponding clientB in brokerB.routes.  
Am I understand right?  Since when I start two brokers and one router, once I send a sub message to one of the brokers, the other will be panic. The error message tells me it is due to the client.session is nil when doing ```c.session.AddTopic(topic, qoss[i])``` in _ProcessSubscribe_

I am sorry if it bothers you too much, since I am very new to MQTT protocol.

**Comment by chowyu08** [comment]
yes,  Sorry to mislead you

**Comment by husy1994** [comment]
> yes, Sorry to mislead you

so , should I change the `b.routes.Range` to `b.remotes.Range`?
