### ISSUE TITLE
Can you give a conf of auth user password

### ISSUE THREAD

**Issue by careylipu** [fhmq/hmq#49]
Can you give a conf of auth user password

**Comment by chowyu08** [comment]
You need to implement this interface [https://github.com/fhmq/hmq/blob/master/plugins/auth/auth.go#L11](url)
 and config it in [https://github.com/fhmq/hmq/blob/master/plugins/auth/auth.go#L17](url)

**Comment by Archie1978** [comment]
Hello chowyu08, I have the same worries as careylipu. I installed the old version, with a conf file.
Can I add file authentication into github.com/fhmq/hmq/plugins/auth ?

**Comment by chowyu08** [comment]
sorry, I do not have much time to do it, later I will take a time do it

**Comment by chowyu08** [comment]
done

**Comment by reejinbouk** [comment]
Hello,
please provide example config or go code running server with auth login and password?
thank you!
