### ISSUE TITLE
[Question] What about using Zap logger? 

### ISSUE THREAD

**Issue by MarcMagnin** [fhmq/hmq#5]
Hey,
Zap logger is a pretty fast / light logger and I think it would be a good fit for an MQTT broker:
https://github.com/uber-go/zap

Let me know what you think about it. I could raise a PR to implement it.

Regards

**Comment by chowyu08** [comment]
Recently, I also want to change a logging tool, very grateful for your recommendation and your PR

**Comment by MarcMagnin** [comment]
I'll go ahead then and implement it.

**Comment by MarcMagnin** [comment]
Btw @chowyu08 on which branch do you recommend to work on?
