### ISSUE TITLE
go get fails; go run fails

### ISSUE THREAD

**Issue by creeble** [fhmq/hmq#50]
<pre>
go get github.com/fhmq/hmq
package context: unrecognized import path "context" (import path does not begin with hostname)
</pre>

But it downloads fine.  Then:
<pre>
go run main.go 
# github.com/fhmq/hmq/plugins/authhttp
plugins/authhttp/authhttp.go:51:19: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport
</pre>
This is running on Ubuntu 18.04, go version go1.10.4 linux/amd64.

Bit of a go newb, so not sure whether these are configuration errors or something else.

**Comment by chowyu08** [comment]
could you try go 1.12 ?

**Comment by creeble** [comment]
Okay, yes, it seems to run with go 1.12.
