### ISSUE TITLE
Regression: Not Authorized when auth not specified and username blank

### ISSUE THREAD

**Issue by pinchpe** [fhmq/hmq#54]
The recent work on adding auth.go seems to have caused a regression, trying to connect to the broker returns an error "Not Authorized"

In broker.go handleConnection()

```
   if typ == CLIENT && !b.CheckConnectAuth(string(msg.ClientIdentifier), string(msg.Username), string(msg.Password)) {
                connack.ReturnCode = packets.ErrRefusedNotAuthorised

```
Unfortunately CheckConnAuth() is not checking for the auth to be the mock auth:

```
func (b *Broker) CheckConnectAuth(clientID, username, password string) bool {
        if b.auth != nil {
                if clientID == "" || username == "" {
                        return false
                }
                return b.auth.CheckConnect(clientID, username, password)
        }

        return true

}
```

In this case b.auth is not nil because it's the mock auth, and clientID and username are blank so "return false".  The mock auth CheckConnect() always returns true which is what we want in this case.

Workaround - make sure client sets the client id and username to something.

**Comment by chowyu08** [comment]
fixd
