### ISSUE TITLE
error default path for kafka plugins

### ISSUE THREAD

**Issue by jerry-chao** [fhmq/hmq#66]
## Environment

- hmq version: 68cd5e94a44c5a856f096a9cf8cb54cd6c3f8ea8
- go version: go1.13.3
- OS: MacOsx 
- Installed from: source

## Bug description

https://github.com/fhmq/hmq/blob/68cd5e94a44c5a856f096a9cf8cb54cd6c3f8ea8/plugins/bridge/kafka.go#L32

the config for plugin kafka is at $PROJECT_ROOT/plugins/bridge/kafka/kafka.json , but the default still be $PROJECT_ROOT/plugins/mq/kafka/kafka.json

**Comment by chowyu08** [comment]
thanks, fixed it
