### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by jvmatl** [fhmq/hmq#67]
Hello, the LICENSE file has the Apache license, but your main.go still has a custom copyright notice/license text:

```
/* Copyright (c) 2018, joy.zhou <chowyu08@gmail.com>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.
*/
```

Would you mind removing the conflicting license so your intended license is clear?

**Comment by chowyu08** [comment]
could you request  pr?
