### ISSUE TITLE
Whether auth of broker can be exported?

### ISSUE THREAD

**Issue by weipsys** [fhmq/hmq#77]
Whether auth of broker can be exported, I need to decide for myself whether to allow clients to connect/sub/pub

https://github.com/fhmq/hmq/blob/master/broker/broker.go#L47

https://github.com/fhmq/hmq/blob/master/broker/broker.go#L95

**Comment by weipsys** [comment]
not just auth by http or file, I need to decide for myself whether to allow clients to connect/sub/pub by my code

**Comment by chowyu08** [comment]
sorry, from now the only way is add code here [https://github.com/fhmq/hmq/blob/master/plugins/auth/auth.go#L18](url)

bridge is same.


welcome for pr, thanks
