### ISSUE TITLE
Incorrect version for github.com/satori/go.uuid package in go.mod

### ISSUE THREAD

**Issue by imran-cfa** [fhmq/hmq#88]
File go.mod is pointing to an older version of the uuid package i.e `github.com/satori/go.uuid v1.2.0` which returns only one value for the call uuid.NewV4(). This causes the following compile error for the line `id, err := uuid.NewV4()`

` # github.com/fhmq/hmq/broker
broker/comm.go:117:10: assignment mismatch: 2 variables but uuid.NewV4 returns 1 values`

The problem can be fixed by fetching the tip of the master from uuid package which has not been tagged in the project. Running the command `go mod download github.com/satori/go.uuid@master` while in the hmq project directory will get the latest commit from master branch of uuid package and will also fix the hmq's go.mod file with pseudo version number as follows: [more info](https://tip.golang.org/cmd/go/#hdr-Pseudo_versions)

`github.com/satori/go.uuid v1.2.1-0.20181028125025-b2ce2384e17b`

**Comment by jpramirez** [comment]
A proposal could be just to update this package to use the latest version
the change should be minimal as the new satori package does not return and error 
From this to:
`
func GenUniqueId() string {
	id, err := uuid.NewV4()
	if err != nil {
		log.Error("uuid.NewV4() return error: " + err.Error())
	}
	return id.String()
}
`
to this

`
func GenUniqueId() string {
	id := uuid.NewV4()
	return id.String()
}
`

I guess that is better to have this package updated if the fix is minimal

Will push a PR with this comment

**Comment by imran-cfa** [comment]
My recommendation would be not to change the function call and just update go.mod to point to the latest commit in satori package as follows. The latest non-tagged commit in master branch of satori correctly returns 2 values. 

github.com/satori/go.uuid v1.2.1-0.20181028125025-b2ce2384e17b
